minio:
  bucket:
    name: instagram
  default:
    folder: "/"
  access:
    name: admin
    secret: password

  url: http://127.0.0.1:9000

---
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    tags:
      application: MonitoringInstagramSpringDemoProject
    enable:
      jvm: true
